apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-pipeline-run-creator
  namespace: tekton
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineresources", "taskruns"]
    verbs: ["create"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines", "tasks", "clustertasks"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"] # To allow access to azure-devops-git-secret
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers", "interceptors"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["clustertriggerbindings", "clusterinterceptors", "interceptors"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-sa-binding
  namespace: tekton
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
    namespace: tekton
roleRef:
  kind: Role
  name: tekton-pipeline-run-creator
  apiGroup: rbac.authorization.k8s.io
